### ISSUE TITLE
Not a real Issue, but a Question :)

### ISSUE THREAD

**Issue by Troox73** [Hyphie24/Overachiever#19]
Can you create a WOTLK Classic Version of this cool Addon? Maybe... ^^

**Comment by Hyphie24** [comment]
Current version "should" still work (will have mostly the same coding with some achieves being moved from FoS to current). I wasn't in the BETA and haven't had a chance to get around in the PTR before they shut it down. 

Once live servers go up with 3.0 Tuesday, I should be able to get around and fix issues over the next week or 2.

Unless something is severely broken *fingers crossed*

**Comment by Hyphie24** [comment]
Follow-up, will take a bit more work than expected. Having to figure out a way to disable the guild achievements and account wide achievement (since those where not part of Wrath with current build)

May have to build around the original version from patch 3.0 to work with Classic.

Simple terms, it is a lot different from retail, but in retail news I am adding items from Dragonflight into it and maybe I'll get lucky and get beta (not holding hopes)

**Comment by Hyphie24** [comment]
Got it working, trying to get the tabs to show up right now, but it is working at the moment, I do not have multiple toons on classic to try out (going by a created level 70 on PTR) Pushing a beta of it right now to get some testers while I'm working on getting the suggestions, search & watch tabs to show.

<img src="https://i.ibb.co/C1sfVc0/Wrath-Classic-1.png" alt="Wrath-Classic-1" border="0">

**Comment by Hyphie24** [comment]
https://github.com/Hyphie24/Overachiever_Wrath Wrath Classic Github

WIll be closing this issue on Saturday Morning, please post any and all issues on the 2nd github. Thank you :D
